# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-09 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否放上品牌特卖')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategoryAll', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'goods_goodsbrand',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='city',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='country',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='district',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='province',
        ),
    ]
