# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200109_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategoryall',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='图标'),
        ),
    ]
