# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodscategoryall_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategoryall',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否放在首页分类展示'),
        ),
    ]
