# Generated by Django 2.2.9 on 2020-01-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodscategoryall_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsimage',
            name='index',
            field=models.IntegerField(default=0, verbose_name='轮播顺序'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=True, related_name='catelogys', to='goods.GoodsCategoryAll', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='brands', to='goods.GoodsCategoryAll', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=True, related_name='images', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
