# Generated by Django 2.2.9 on 2020-01-19 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200115_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='Specifications',
        ),
        migrations.CreateModel(
            name='Goodsspecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_text', models.CharField(max_length=100, verbose_name='商品规格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=True, related_name='specification', to='goods.Goods', verbose_name='商品')),
            ],
        ),
    ]
