# Generated by Django 2.2.9 on 2020-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200119_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='history_price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='shop_price',
        ),
        migrations.RemoveField(
            model_name='goodsspecification',
            name='price',
        ),
        migrations.AddField(
            model_name='goodsspecification',
            name='promotion_price',
            field=models.FloatField(blank=True, null=True, verbose_name='促销价格'),
        ),
        migrations.AddField(
            model_name='goodsspecification',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='商品价格'),
        ),
    ]
