# Generated by Django 2.2.9 on 2020-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200119_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='Storage_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_front_image',
        ),
        migrations.AddField(
            model_name='goods',
            name='storage_type',
            field=models.CharField(default='常温', max_length=30, verbose_name='存储方式'),
        ),
    ]
