# Generated by Django 2.2.9 on 2020-02-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200119_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=100, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=100, verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=100, verbose_name='商品销售量'),
        ),
    ]
