# Generated by Django 2.2.9 on 2020-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200211_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='当前价格'),
        ),
    ]
