# Generated by Django 2.2.9 on 2020-03-10 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='integralgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/integralgoods/', verbose_name='图片')),
                ('specification', models.CharField(max_length=100, verbose_name='商品的规格')),
                ('goods_num', models.IntegerField(default=100, verbose_name='库存数')),
                ('integral', models.CharField(max_length=100, verbose_name='需要的积分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '积分商品',
                'verbose_name_plural': '积分商品',
            },
        ),
    ]
