# Generated by Django 2.2.9 on 2020-02-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200108_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='post_script',
        ),
    ]
