# Generated by Django 2.2.9 on 2020-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_orderinfo_post_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='takegoods_status',
            field=models.CharField(choices=[('online', '线上'), ('self_mention', '线下自提')], default='online', max_length=30, verbose_name='提取方式'),
        ),
    ]
