# Generated by Django 2.2.9 on 2020-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_orderinfo_takegoods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSED', '超时关闭'), ('paying', '待支付'), ('refunding', '待退款'), ('refund', '退款成功'), ('loading', '等待配送'), ('writing', '待评价'), ('TRADE_SUCCESS', '订单已完成')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
