# Generated by Django 2.2.9 on 2020-02-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20200224_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='selected',
        ),
    ]
