# Generated by Django 2.2.9 on 2020-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_remove_shoppingcart_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='gettime',
            field=models.CharField(default='', max_length=100, verbose_name='提取时间'),
        ),
    ]
