# Generated by Django 2.2.9 on 2020-03-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0010_orderinfo_gettime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='operator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
