# Generated by Django 2.2.9 on 2020-03-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20200307_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('refunding', '退款申请中'), ('fefunding', '退款成功，交易结束'), ('Picking', '订单商品配货中'), ('checkout', '商品正在进行第二次检验'), ('Delivery', '订单商品送货中'), ('trade_evaluate', '交易结束等待评价'), ('TRADE_SUCCESS', '交易结束')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
