# Generated by Django 2.2.9 on 2020-03-08 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20200308_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='operator_phone',
            field=models.CharField(default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='operator',
            field=models.ForeignKey(default='', null=True, on_delete=True, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='订单配送人员'),
        ),
    ]
