# Generated by Django 2.2.9 on 2020-03-09 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_auto_20200308_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='operator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=True, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='订单配送人员'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='operator_phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='配送人员手机号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('refunding', '退款申请中'), ('fefunding', '退款成功，交易结束'), ('Picking', '订单商品配货中'), ('Picking_complete', '订单配货完成'), ('checkout', '商品二次检验完'), ('Delivery', '订单商品送货中'), ('trade_evaluate', '交易结束等待评价'), ('TRADE_SUCCESS', '交易结束')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
