# Generated by Django 2.2.9 on 2020-03-10 15:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0016_integralgoods'),
        ('trade', '0016_auto_20200309_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='integralgood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.CreateModel(
            name='integralgoodsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='购买数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('integralgoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.integralgoods', verbose_name='积分商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '兑换积分商品',
                'verbose_name_plural': '兑换积分商品',
                'unique_together': {('user', 'integralgoods')},
            },
        ),
    ]
