# Generated by Django 2.2.9 on 2020-03-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20200310_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='integralgood',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.integralgoods', verbose_name='积分兑换商品'),
        ),
    ]
