# Generated by Django 2.2.9 on 2020-03-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_auto_20200310_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='integralgood',
        ),
    ]
