# Generated by Django 2.2.9 on 2020-03-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_integralgoods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0021_auto_20200310_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='integralgoodscart',
            name='intgeralgoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='integralgood',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterUniqueTogether(
            name='integralgoodscart',
            unique_together={('user', 'intgeralgoods')},
        ),
        migrations.RemoveField(
            model_name='integralgoodscart',
            name='goods',
        ),
    ]
