# Generated by Django 2.2.9 on 2020-03-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_integralgoods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0022_auto_20200310_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integralgoodscart',
            options={'verbose_name': '用户积分商品', 'verbose_name_plural': '用户积分商品'},
        ),
        migrations.RenameField(
            model_name='integralgoodscart',
            old_name='intgeralgoods',
            new_name='goods',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='integralgood',
        ),
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterUniqueTogether(
            name='integralgoodscart',
            unique_together={('user', 'goods')},
        ),
    ]
