# Generated by Django 2.2.9 on 2020-03-10 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_integralgoods'),
        ('trade', '0027_auto_20200310_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='inter_goods',
        ),
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.CreateModel(
            name='Orderintergralgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='积分兑换商品数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('inter_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intergralgoods', to='trade.OrderInfo', verbose_name='订单信息')),
            ],
            options={
                'verbose_name': '积分兑换商品',
                'verbose_name_plural': '积分兑换商品',
            },
        ),
    ]
