# Generated by Django 2.2.9 on 2020-03-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0036_auto_20200315_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='gettime',
            field=models.CharField(default='', max_length=100, verbose_name='取得订单货品时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='singer_mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='takegoods_status',
            field=models.CharField(blank=True, choices=[('online', '线上'), ('self_mention', '线下自提')], default='online', max_length=30, verbose_name='提取方式'),
        ),
        migrations.AlterField(
            model_name='orderintergralgoods',
            name='inter_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品'),
        ),
    ]
