# Generated by Django 2.2.9 on 2020-03-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0038_auto_20200315_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='distributor',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='订单分配员'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='inspecter',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='订单二次拣货人'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='picker',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='订单拣货人'),
        ),
        migrations.AlterField(
            model_name='orderintergralgoods',
            name='inter_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品'),
        ),
    ]
