# Generated by Django 2.2.9 on 2020-03-16 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0040_auto_20200315_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='doubttext',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='订单疑问原因'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='isdoubt',
            field=models.BooleanField(default=False, verbose_name='是否为有疑问订单'),
        ),
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='orderintergralgoods',
            name='inter_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品'),
        ),
    ]
