# Generated by Django 2.2.9 on 2020-03-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0044_auto_20200316_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='operator_phone',
            new_name='deliveryman_phone',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='operator',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='deliveryman',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='订单配送人员'),
        ),
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='orderintergralgoods',
            name='inter_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品'),
        ),
    ]
