# Generated by Django 2.2.9 on 2020-03-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0047_auto_20200316_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralgoodscart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分兑换商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('refunding', '退款申请中'), ('fefunding', '退款成功，交易结束'), ('Picking', '订单商品配货中'), ('Picking_complete', '订单配货完成'), ('checkout', '商品二次检验完'), ('Delivery', '等待送货员提取商品'), ('Deliverying', '订单商品送货中'), ('trade_evaluate', '交易结束等待评价'), ('TRADE_SUCCESS', '交易结束')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderintergralgoods',
            name='inter_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Integralgoods', verbose_name='积分商品'),
        ),
    ]
