# Generated by Django 2.2.9 on 2020-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200307_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_status',
            field=models.CharField(choices=[('primary', '初级会员'), ('senior', '高级会员')], default='primary', max_length=30, verbose_name='会员等级'),
        ),
    ]
