# Generated by Django 2.2.9 on 2020-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isfaith',
            field=models.BooleanField(default=False, verbose_name='是否违约'),
        ),
    ]
