# Generated by Django 2.2.9 on 2020-03-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200307_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ordinary_user', '普通用户'), ('order_distributor', '订单分配员'), ('shop_inspector', '超市自提商品管理员'), ('manager', '后台管理员'), ('boss', '超级管理员')], default='ordinary_user', max_length=30, verbose_name='角色'),
        ),
    ]
