# Generated by Django 2.2.9 on 2020-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200315_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ordinary_user', '普通用户'), ('order_distributor', '订单分配员'), ('picker', '商品拣货员'), ('delivery', '送货员'), ('shop_inspector', '超市自提商品管理员'), ('manager', '后台管理员'), ('boss', '超级管理员')], default='ordinary_user', max_length=30, verbose_name='角色'),
        ),
    ]
