# Generated by Django 2.2.9 on 2020-03-16 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilevisitnumber',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间'),
        ),
        migrations.AddField(
            model_name='pcvisitnumber',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间'),
        ),
    ]
